# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [6]:
import numpy as np
#Solution
ar=np.linspace(10,29,29)
print('Length of array',len(ar))
print('Array is',ar)



Length of array 29
Array is [10.         10.67857143 11.35714286 12.03571429 12.71428571 13.39285714
 14.07142857 14.75       15.42857143 16.10714286 16.78571429 17.46428571
 18.14285714 18.82142857 19.5        20.17857143 20.85714286 21.53571429
 22.21428571 22.89285714 23.57142857 24.25       24.92857143 25.60714286
 26.28571429 26.96428571 27.64285714 28.32142857 29.        ]


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [9]:
# Solution
ar=np.arange(1,50,2)
print('Array is',ar)
print('Length of array is',len(ar))


Array is [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
Length of array is 25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [11]:
# Solution
ar=np.linspace(4,7,27)
print('Array is',ar)
    


Array is [4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [15]:
# Solution
mat1=np.round(np.random.rand(5,4),2)
print(mat1)


[[0.65 0.5  0.36 0.21]
 [0.26 0.58 0.95 0.29]
 [0.4  0.36 0.05 0.02]
 [0.82 0.65 0.97 0.09]
 [0.39 0.14 0.88 0.88]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [16]:
# Solution
mat1=np.random.randint(5,15,size=(5,5))
print(mat1)



[[10 13 11 11  9]
 [13 11  8  8  7]
 [10  6 13 11 11]
 [14  9  7  6  5]
 [ 7 10  6 14 10]]


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [29]:
# Solution
arr=np.zeros([np.random.randint(20)],dtype='int32')
print(arr)



[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [30]:
# Solution
arr=[[np.ones([np.random.randint(10)],dtype='float32')],np.ones([np.random.randint(1,20)],dtype='float32')]

arr

[[array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)],
 array([1., 1., 1., 1., 1., 1.], dtype=float32)]

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [12]:
# Solution
ar1=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(ar1)
print(ar1.shape)
print(type(ar1))
print(ar1.dtype)



[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
(5, 5)
<class 'numpy.ndarray'>
int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [48]:
# Solution
a=int((len(ar1)-1)/2)
mid=ar1[a,a]
print(mid)



3


#### 10. Print the all the elements of 3rd row of the matrix

In [51]:
# Solution
ar2=ar1[[2],:]
ar2


array([[ 5,  7,  3, 76,  3]])

#### 11. Print the all the elements of 4th columns of the matrix

In [53]:
# Solution

ar3=ar1[:,3]
ar3


array([34, 65, 76, 54,  5])

#### 12. Print the 4 corner pixels of the matrix

In [3]:
# Solution
arr=ar1[[0,len(ar1)-1],:]
arr
arr2=arr[:,[0,len(arr)-1]]
arr2


array([[ 9, 25],
       [23, 12]])

#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [13]:
# Solution 

m1=ar1[0:2,2:4]
print(m1)
m2=ar1[3:,:2]
print(m2)
m3=ar1[2:,2:]
print(m3)


[[50 34]
 [34 65]]
[[ 7  8]
 [23 12]]
[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [64]:
# Solution
mat1=m1.reshape(1,-1)
print(mat1)
mat2=m2.reshape(1,-1)
print(mat2)
mat3=m3.reshape(1,-1)
print(mat3)



[[50 34 34 65]]
[[ 7  8 23 12]]
[[ 3 76  3  6 54  6  8  5  8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [14]:
import numpy as np
# Solution
m1=np.squeeze(m1)
m2=np.squeeze(m2)
hormat=np.hstack((m1,m2))
vermat=np.vstack((m1,m2))
print(hormat)
print(vermat)



[[50 34  7  8]
 [34 65 23 12]]
[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [15]:
# Solution
addmat=np.add(m1,m2)
print(addmat)
submat=np.subtract(m1,m2)
print(submat)
mulmat=np.multiply(m1,m2)
print(mulmat)
divadd=np.divide(m1,m2)
print(divadd)



[[57 42]
 [57 77]]
[[43 26]
 [11 53]]
[[350 272]
 [782 780]]
[[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [16]:
# Solution
modifiedmat=m3[[1,2],[0,1]]
#print(modifiedmat)
add1mat=np.add(m1,modifiedmat)
print(add1mat)
m3_new=m3[1:,:-1]
print(m3_new)
print(m1+m3_new)

[[56 39]
 [40 70]]
[[ 6 54]
 [ 8  5]]
[[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [38]:
# Solution

me1=np.mean([m1[:,[0]]])
me2=np.mean([m1[:,[1]]])
m=np.array([me1,me2])
print(m)
m4=np.vstack((m1,m))
print(m4)




[42.  49.5]
[[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [39]:
# Solution

matrixmul=np.matmul(m3,m4)
print(matrixmul)


[[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [19]:
# Solution

mat_me=np.mean(ar1,axis=1)
mat_var=np.var(ar1,axis=1)
mat_std=np.std(ar1,axis=1)
print(np.round((mat_me),2))
print(np.round((mat_var),2))
print(np.round((mat_std),2))


[32.6 27.6 18.8 16.2 11.2]
[214.64 548.24 820.16 357.76  39.76]
[14.65 23.41 28.64 18.91  6.31]


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [17]:
# Solution 
score=np.array([['MSD',54,60,10,65],['Kholi',102,2,78,32],['Rohit',3,110,1,92],
                ['Rahul',56,6,12,42],['Dhawan',12,8,22,11]])
print(score)
run=score[:,1:5]
print("\n The run matrix \n",run)
run1=run.astype('int32')  # to make the run as integer
print('\n The run matrix in integer \n',run1)

avg=run1.mean(axis=1)
print("\n The average score for each player \n",avg)

avg1=avg.reshape([5,1])
score_avg=np.concatenate([score,avg1],axis=1) # concatenating the average value as last column
print('\n Players score with Average \n',score_avg)

ind=avg.argsort() # to get the index based on sort (ascending)
final_list=score_avg[ind,:][::-1] #::1 is the operator which sort in a desending way
print('\n Final player oder list based on their average \n',final_list)


[['MSD' '54' '60' '10' '65']
 ['Kholi' '102' '2' '78' '32']
 ['Rohit' '3' '110' '1' '92']
 ['Rahul' '56' '6' '12' '42']
 ['Dhawan' '12' '8' '22' '11']]

 The run matrix 
 [['54' '60' '10' '65']
 ['102' '2' '78' '32']
 ['3' '110' '1' '92']
 ['56' '6' '12' '42']
 ['12' '8' '22' '11']]

 The run matrix in integer 
 [[ 54  60  10  65]
 [102   2  78  32]
 [  3 110   1  92]
 [ 56   6  12  42]
 [ 12   8  22  11]]

 The average score for each player 
 [47.25 53.5  51.5  29.   13.25]

 Players score with Average 
 [['MSD' '54' '60' '10' '65' '47.25']
 ['Kholi' '102' '2' '78' '32' '53.5']
 ['Rohit' '3' '110' '1' '92' '51.5']
 ['Rahul' '56' '6' '12' '42' '29.0']
 ['Dhawan' '12' '8' '22' '11' '13.25']]

 Final player oder list based on their average 
 [['Kholi' '102' '2' '78' '32' '53.5']
 ['Rohit' '3' '110' '1' '92' '51.5']
 ['MSD' '54' '60' '10' '65' '47.25']
 ['Rahul' '56' '6' '12' '42' '29.0']
 ['Dhawan' '12' '8' '22' '11' '13.25']]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [4]:
# Solution
marks=np.array([65,84,47,56,89,98,48,77,80,39])

pass_ind=np.where(marks>=50)
pass_marks=marks[pass_ind]

fail_ind=np.where(marks<50)
fail_marks=marks[fail_ind]

print('The Number of Students passed = ',len(pass_marks))
print('The Number of Students failed = ',len(fail_marks))


The Number of Students passed =  7
The Number of Students failed =  3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [5]:
# Solution

boost_mark=marks.copy()
mercy_ind=np.where((boost_mark>=45) & (boost_mark<=49))
boost_mark[mercy_ind]=boost_mark[mercy_ind]+5

bonus_ind=np.where((boost_mark>80) & (boost_mark<=95))
boost_mark[bonus_ind]=boost_mark[bonus_ind]+5

bonus_ind1=np.where(boost_mark>95)
boost_mark[bonus_ind1]=100

print('Actual Students marks \n',marks)
print('Boosted Students marks \n',boost_mark)

actual_pass_percent=(len(marks[np.where(marks>=50)])/len(marks))*100 
boosted_pass_percent=(len(boost_mark[np.where(boost_mark>=50)])/len(boost_mark))*100 
inc_pass_percent=boosted_pass_percent-actual_pass_percent
print('The increase in pass percentage is : ',inc_pass_percent)


Actual Students marks 
 [65 84 47 56 89 98 48 77 80 39]
Boosted Students marks 
 [ 65  89  52  56  94 100  53  77  80  39]
The increase in pass percentage is :  20.0


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [3]:
# Solution
import numpy as np
import time
x=range(1,60000)
y=range(1,60000)
out=[]

st=time.time()
for i,j in zip(x,y):
    out.append((x[i-1]*x[i-1]+8)/y[i-1])

print('Time taken to complete the computation using LIST is : ', (time.time()-st)*1000)

x_ar=np.arange(1,60000)
y_ar=np.arange(1,60000)
st_ar=time.time()
out_ar=((x_ar*x_ar)+8)/y_ar
print('Time taken to complete the computation using NUMPY ARRAY is : ', (time.time()-st_ar)*1000)



Time taken to complete the computation using LIST is :  293.1938171386719
Time taken to complete the computation using NUMPY ARRAY is :  3.0035972595214844


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [ ]:
# Solution



